title: "Hacking Me"
baseline: "Your blog's butler."
description: "Tools & effective strategies to focus on importnat stuff"
baseurl: "/"
canonicalurl: true
theme: "hyde"
date:
  format: "j F Y"
  timezone: "Europe/Paris"
pagination:
  max: 5
  path: "page"
output:
  formats:
    netlify_redirects:
      mediatype: "text/plain"
      extension: ""
virtualpages:
  admin:
    layout: admin/index
    output: html
    title: "Content Manager (Netlify CMS)"
  home:
    redirect: /
  _redirects:
    output: netlify_redirects
netlify:
  cms:
    path: "admin"
    version: "latest"
  identity:
    version: "v1"
